# Generated by Django 5.2.15 on 2026-07-02 09:47

import django.db.models.deletion
import profiles.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(blank=True, choices=[('masjid', 'Masjid'), ('madrasa', 'Madrasa'), ('ngo', 'NGO'), ('school', 'School'), ('university', 'University'), ('individual', 'Individual')], max_length=20, null=True)),
                ('organization_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=15)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='employers/verification_docs/', validators=[profiles.validators.validate_verification_document_extension, profiles.validators.validate_verification_document_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='locations.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='locations.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='locations.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='locations.village')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
