# Generated by Django 5.2.15 on 2026-07-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal admin-only notes (never shown publicly).'),
        ),
        migrations.AddField(
            model_name='employer',
            name='created_by_admin',
            field=models.BooleanField(default=False, help_text='Created on behalf of the organization by a platform admin.'),
        ),
    ]
