# Generated by Django 5.2.15 on 2026-07-02 08:10

import django.db.models.deletion
import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarseNizami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madrasa_name', models.CharField(max_length=200)),
                ('wifaq_name', models.CharField(blank=True, max_length=200)),
                ('sanad_year', models.PositiveIntegerField(blank=True, null=True, validators=[profiles.validators.validate_education_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dars_nizami_records', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Dars-e-Nizami',
                'verbose_name_plural': 'Dars-e-Nizami records',
                'ordering': [models.OrderBy(models.F('sanad_year'), descending=True, nulls_last=True), '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HifzEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madrasa_name', models.CharField(max_length=200)),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True, validators=[profiles.validators.validate_education_year])),
                ('teacher_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hifz_records', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Hifz education',
                'verbose_name_plural': 'Hifz education records',
                'ordering': [models.OrderBy(models.F('completion_year'), descending=True, nulls_last=True), '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ijazah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('ustad_name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[profiles.validators.validate_education_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ijazah_records', to='profiles.profile')),
            ],
            options={
                'verbose_name_plural': 'Ijazah records',
                'ordering': [models.OrderBy(models.F('year'), descending=True, nulls_last=True), '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MuftiCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madrasa_name', models.CharField(max_length=200)),
                ('takhassus_subject', models.CharField(choices=[('hadith', 'Hadith'), ('fiqh', 'Fiqh'), ('tafsir', 'Tafsir'), ('arabic', 'Arabic'), ('other', 'Other')], max_length=20)),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True, validators=[profiles.validators.validate_education_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mufti_course_records', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Mufti course',
                'verbose_name_plural': 'Mufti course records',
                'ordering': [models.OrderBy(models.F('completion_year'), descending=True, nulls_last=True), '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NazraQirat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nazra', 'Nazra'), ('tajweed', 'Tajweed'), ('qirat', 'Qirat')], max_length=20)),
                ('qirat_type', models.CharField(blank=True, max_length=200, null=True)),
                ('madrasa_or_teacher', models.CharField(blank=True, max_length=200)),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True, validators=[profiles.validators.validate_education_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nazra_qirat_records', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Nazra/Qirat',
                'verbose_name_plural': 'Nazra/Qirat records',
                'ordering': [models.OrderBy(models.F('completion_year'), descending=True, nulls_last=True), '-created_at'],
            },
        ),
    ]
