# Generated by Django 5.2.15 on 2026-07-02 08:21

import django.core.validators
import django.db.models.deletion
import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_darsenizami_hifzeducation_ijazah_mufticourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_urdu', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_urdu', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='audio_sample',
            field=models.FileField(blank=True, null=True, upload_to='profiles/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a']), profiles.validators.validate_audio_file_size]),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='profiles/verification_docs/', validators=[profiles.validators.validate_verification_document_size]),
        ),
        migrations.AddField(
            model_name='profile',
            name='video_sample',
            field=models.FileField(blank=True, null=True, upload_to='profiles/video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi']), profiles.validators.validate_video_file_size]),
        ),
        migrations.CreateModel(
            name='AsriEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('matric', 'Matric'), ('fa', 'FA'), ('ba', 'BA'), ('ma', 'MA'), ('bs', 'BS'), ('mphil', 'MPhil'), ('phd', 'PhD')], max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[profiles.validators.validate_education_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asri_education_records', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Asri education',
                'verbose_name_plural': 'Asri education records',
                'ordering': [models.OrderBy(models.F('year'), descending=True, nulls_last=True), '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.language'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.skill'),
        ),
    ]
