# Generated by Django 5.2.15 on 2026-07-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_language_skill_profile_audio_sample_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cnic',
        ),
    ]
