# Generated by Django 5.2.15 on 2026-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_contact_publicly',
            field=models.BooleanField(default=False, help_text='When verified, allow contact email and WhatsApp on the public profile.'),
        ),
    ]
