# Generated by Django 5.2.15 on 2026-07-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_show_contact_publicly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mufticourse',
            name='takhassus_subject',
            field=models.CharField(choices=[('hadith', 'Hadith'), ('fiqh', 'Fiqh'), ('tafsir', 'Tafsir'), ('arabic', 'Arabic'), ('ifta', 'Ifta'), ('other', 'Other')], max_length=20),
        ),
    ]
