# Generated by Django 5.2.15 on 2026-07-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_mufticourse_takhassus_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
