# Generated by Django 5.2.15 on 2026-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_category',
            field=models.CharField(blank=True, choices=[('imam', 'Imam'), ('muazzin', 'Muazzin'), ('mudarris', 'Mudarris'), ('mufti', 'Mufti'), ('qari', 'Qari'), ('khateeb', 'Khateeb'), ('quran_teacher', 'Quran Teacher'), ('islamic_lecturer', 'Islamic Lecturer'), ('individual', 'Individual'), ('hifz_teacher', 'Hifz Teacher'), ('nazira_teacher', 'Nazira Teacher'), ('aalim', 'Aalim'), ('khadim_masjid', 'Khadim-e-Masjid'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
