# Generated by Django 5.2.15 on 2026-07-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('either', 'Either')], max_length=20, null=True),
        ),
    ]
