# Generated by Django 5.2.15 on 2026-07-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_facebook_url_profile_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mufticourse',
            name='takhassus_subject',
            field=models.CharField(max_length=200),
        ),
    ]
