# Generated by Django 5.2.15 on 2026-07-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('locations', '0001_initial'),
        ('profiles', '0003_language_skill_profile_audio_sample_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('imam', 'Imam'), ('muazzin', 'Muazzin'), ('mudarris', 'Mudarris'), ('mufti', 'Mufti'), ('qari', 'Qari'), ('khateeb', 'Khateeb'), ('quran_teacher', 'Quran Teacher'), ('islamic_lecturer', 'Islamic Lecturer'), ('individual', 'Individual')], max_length=30)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('accommodation_provided', models.BooleanField(default=False)),
                ('meals_provided', models.BooleanField(default=False)),
                ('experience_required', models.CharField(choices=[('fresh', 'Fresh'), ('1_3_years', '1–3 years'), ('3_5_years', '3–5 years'), ('5_plus_years', '5+ years')], max_length=20)),
                ('sect', models.CharField(blank=True, choices=[('deobandi', 'Deobandi'), ('barelvi', 'Barelvi'), ('ahle_hadith', 'Ahle Hadith'), ('shia', 'Shia'), ('other', 'Other'), ('not_specified', 'Not specified')], help_text='Optional. Sensitive attribute — never required.', max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('filled', 'Filled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='locations.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='locations.district')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='employers.employer')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='locations.province')),
                ('required_languages', models.ManyToManyField(blank=True, related_name='job_postings', to='profiles.language')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
