# Generated by Django 5.2.15 on 2026-07-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('filled', 'Filled'), ('removed', 'Removed')], default='active', max_length=20),
        ),
    ]
