# Generated by Django 5.2.15 on 2026-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_enable_pg_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='category',
            field=models.CharField(choices=[('imam', 'Imam'), ('muazzin', 'Muazzin'), ('mudarris', 'Mudarris'), ('mufti', 'Mufti'), ('qari', 'Qari'), ('khateeb', 'Khateeb'), ('quran_teacher', 'Quran Teacher'), ('islamic_lecturer', 'Islamic Lecturer'), ('individual', 'Individual'), ('hifz_teacher', 'Hifz Teacher'), ('nazira_teacher', 'Nazira Teacher'), ('aalim', 'Aalim'), ('khadim_masjid', 'Khadim-e-Masjid'), ('other', 'Other')], max_length=30),
        ),
    ]
