# Generated by Django 5.2.15 on 2026-07-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobposting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time')], default='full_time', max_length=20),
        ),
    ]
